### ISSUE TITLE
Replace Twitter with Mastodon

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters#1175]
We get signal. [Main screen turn on.](https://en.m.wikipedia.org/wiki/All_your_base_are_belong_to_us)

```
Hello,

We’ve noticed your usage of the Twitter API may be a good fit for our Basic tier which costs $100 a month via <a href="http://localhost:3000/en/portal/products/basic">our website</a>. The Basic tier includes:

Access to suite of v2 endpoints
3,000 Tweets per month - posting limit at the user level
50,000 Tweets per month - posting limit at the app level
10,000 Tweets per month read-limit rate cap
2 app IDs
Login with Twitter

We recommend you migrate to <a href="http://localhost:3000/en/portal/products/basic">Basic</a> immediately so you can continue to provide uninterrupted service to your app and customers because of the recently announced shut down of our current Twitter API access plans. Please continue to follow @TwitterDev for the latest updates.

<a href="http://localhost:3000/en/portal/products/basic">Sign up here!</a>

http://developer.twitter.com | @twitterdev - http://twitter.com/twitterdev
X Corp. 1355 Market Street, San Francisco, CA 94103
```

As tempting as it might be to triple our hosting costs to give more free content to Twitter, the links all go to my lobsters development server. This can only be a subtle message that I should drop twitter support in favor of mastodon. (But Elon, if you’d like us to keep supporting Twitter, I’d be happy to for $8/mo. Bring cash. [I don’t make change.](https://www.youtube.com/watch?v=Sp5xjxGw_bU))

We’ve seen this coming (if not this level of technical and entrepreneurial ineptitude) for a while, so this issue rounds up the in-progress work and surveys the remaining.

To-do list:

 - [x] Ask for lobsters@botsin.space username, seems to be where most bots live
 - [x] Create list for Lobsters users - nope, see comment below
 - [x] OAuth users against Mastodon usernames #1141, #1173 
 - [x] Port `script/post_to_twitter` #1159 to post to Mastodon
 - [ ] ~Update `post_to_twitter` to link to Mastodon posts to migrate people from the dumpster fire~ api broken before I could do this
 - [x] Port `script/sync_twitter_users` to sync authed users as follows
 - [ ] ~Deauth all twitter oauths so we stop appearing in their settings~ API broken before I could do this
 - [x] Remove twitter cron jobs from ansible
 - [x] Remove twitter accounts from profiles and `/settings`
 - [x] Migration to remove twitter accounts from db, message users about Mastodon
 - [x] Pour one out for a gift economy that a [fool decided to strip-mine](https://en.m.wikipedia.org/wiki/The_Goose_that_Laid_the_Golden_Eggs)

Related but not required:
 - [ ] Tool for finding inviters #558 
 - [ ] More ActivityPub support #499

**Comment by pushcx** [comment]
Emailed @albino to ask about the username he has [his bot](https://github.com/albino/lobstertoot) on now.

**Comment by albino** [comment]
Good morning @pushcx! This looks like a great project. I haven't received any emails from you, however (my email host is located in Ukraine and sometimes Russian attacks take out the electrical/internet infrastructure – try albino AT autistici DOT org instead).

In general I'd be very happy to hand over the account! I will lose access to the box on which the bot currently lives in a couple months, so this is a great time to migrate.

The only thing I'd ask is that you keep the small Ukrainian flag in the account's bio. I put it there on 24/02/2022 and resolved not to remove it until Ukraine is free and whole. I understand it's a bit of an unconventional request, but I feel somewhat attached to the account having registered it in the early days of Mastodon and maintained it for the past six years. Would you consider that?

All the best
Lawrence

**Comment by pushcx** [comment]
I emailed just before I left that comment, I’ll try your alternate address now so you can see what I tried to send.

I think maintaining the 🇺🇦 flag as you describe is totally fair and I’d be happy to do it. I can only wish you and your country good luck in the face of this evil.

**Comment by albino** [comment]
Great! I have emailed you credentials. Enjoy!

**Comment by pushcx** [comment]
We’ve handed off the account. Thanks again, @albino.

Mastodon announcement: https://botsin.space/@lobsters/110305159035298486

Twitter announcement: https://twitter.com/lobsters/status/1653767955681800194

**Comment by pushcx** [comment]
Mastodon lists [can’t be public](https://github.com/mastodon/mastodon/issues/8208), but [follows are](https://botsin.space/@lobsters/following), so I’ve updated the task to reflect that @lobsters should follow authed users, not maintain a list.

**Comment by solfisher** [comment]
would it be reasonable to aim to support other popular fediverse software as well? [Akkoma](https://akkoma.social) has a similar API to Mastodon's, but apps like [Misskey](https://misskey-hub.net)'s (and its forks Foundkey and Calckey) were built from the ground up. still, would be neat to be able to post directly to them.

**Comment by iacore** [comment]
Please support ActivityPub, that allows commenting with accounts from other domains.

**Comment by albino** [comment]
Hi @pushcx, I transferred control of the lobsters account to you some months ago, but you haven't yet used it for anything. My bot is still the only application posting to the account. That's not really cool, because I no longer have access to go in and fix things when they go wrong. I don't want to stop the bot working because it seems like people do use it. Please can you either make plans to take over the operation of the bot, or transfer control back to me? Of course, once you've implemented your own bot, I'll be more than happy to hand control back over to you.

**Comment by pushcx** [comment]
I've finished and merged #1173 for authing Mastodon accounts, which is part of pulling the functionality in to the site properly. Sorry this was outstanding, @albino, I'm trying to move things over the next few days here.

**Comment by pushcx** [comment]
I’ve pushed b8aaae38 with a new `script/mastodon_sync_list.rb`.

Mastodon requires following users to add them to a list, which may mean the user needs to approve the follow (depending on server and user configs), so our list will never be quite accurate.

**Comment by pushcx** [comment]
I deployed 892997eca4ed7e7ffa6dc44d109731bbdeca4851.
